### ISSUE TITLE
When typing first letter in search, 3 distinct render flashes

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#607]
When you type first letter in search, there are 3 distinct render flashes that happen in a split second. We should only render once for each keypress. cc @Gozala

**Comment by gordonbrander** [comment]
Maybe related? https://github.com/mozilla/browser.html/issues/604

**Comment by Gozala** [comment]
@gordonbrander it's down to at max 2 right now, the third flash was indeed related to #604. So what happens now is we do run two concurrent queries search and history, both results come async so once we get first result we render once we get the second result we update suggestions to include those as well. We could combine two queries so we render only once but that would also mean that we delay results until both queries finished and that may not be ideal as one may take a lot longer then the other and it also may come back with no results so we basically kept user waiting for no real benefit.

**Comment by gordonbrander** [comment]
@Gozala I think it's ok to change the search suggestions async. The biggest issue is when the box that contains the search results does a render flash (in case of no results). This creates a very janky experience. I think it may no longer happen now that we've fixed #604?

**Comment by paulrouget** [comment]
Could #611 be related too? I think it's 3 flashes as well.

**Comment by Gozala** [comment]
@gordonbrander so if I understand you correctly main issue is that suggestion box would become empty and then got populated again. If so that indeed should be fixed by #604 

current behavior should be something like this:

1. Type `a`
2. See 6 search suggestions
3. Bottom 3 search suggestions get replaced by 3 history suggestions and top hit suggestion is prepended to the top.

P.S. It also could be other way round when you see history suggestions first and they get replaced with searches.

**Comment by Gozala** [comment]
> Could #611 be related too? I think it's 3 flashes as well.

I still see it so I don't think so, also location bar and suggestions are not really related so it's likely something else.

**Comment by gordonbrander** [comment]
This behavior sounds fine https://github.com/mozilla/browser.html/issues/607#issuecomment-132719277

**Comment by Gozala** [comment]
Ok closing this one out then, feel free to reopen if you observe more flashes. If you do please try to capture reproducible scenario.
